### ISSUE TITLE
Change enchant compatibility check to not depend on target

### ISSUE THREAD

**Issue by Lyof429** [Hiiragi283/Enchanting-Smith#1]
At this line, enchantment.target.isAcceptableItem(stack.getItem()) should be changed to enchantment.isAcceptableItem(stack) (or stack.getItem())

This would make the enchant compatibility check to actually depend on the enchantment and not its target
Doesn't change anything for vanilla enchantments but modded ones may want some enchants to only be applicable to specific itemstacks or other precise conditions: an enchantment target's isAcceptableItem can't be overridden and making new ones is extremely complicated, while enchantment.isAcceptableItem is easily modified in the enchant's class.
Furthermore, this method defaults to enchantment.target.isAcceptableItem so this wouldn't break anything, only allow modded enchants to work better with your system

https://github.com/Hiiragi283/Enchanting-Smith/blob/fabric_1201/src/main/java/io/github/hiiragi283/enchsmith/SmithingUpgradeRecipe.java#L77

Partly saying this because I'd love to use this mod in a modpack, but it has a few special item types that don't have a custom enchantment target but instead use the enchant's isAcceptableItem method directly 
(So they break)

**Comment by Hiiragi283** [comment]
Thank you for sending issue!
I have fixed on commit 60c7739, then release updated jar on Modrinth
